I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 136, in script call
    call d1season
  File "game/script.rpy", line 136, in script call
    call d1season
ScriptError: could not find label 'd1season'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 136, in script call
    call d1season
  File "C:\Users\brade\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 136, in script call
    call d1season
  File "C:\Users\brade\Desktop\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd1season'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
We're Wolves 1.0
Mon Apr 24 19:30:30 2023
